apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopsphere
  namespace: shopsphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopsphere
  template:
    metadata:
      labels:
        app: shopsphere
    spec:
      containers:
        - name: shopsphere
          image: 847776737366.dkr.ecr.us-east-2.amazonaws.com/shopsphere:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: shopsphere-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
