apiVersion: v1
kind: Service
metadata:
  name: shopsphere
  namespace: shopsphere
spec:
  selector:
    app: shopsphere
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
